server:
  port: 8080

spring:
  datasource:
    username: postgres
    password: 666666
    url: jdbc:postgresql://localhost:5432/school1
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    cache:
      type: ehcache
      ehcache:
        config: classpath:ehcache.xml

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  sql:
    init:
      mode: always

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

